// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDATLZrlaLsmqgJgqJDFnLx5QG9vsUnhAE',
    appId: '1:544547051207:web:175a5894cd9b1f8b6b10e2',
    messagingSenderId: '544547051207',
    projectId: 'expense-tracker-d0642',
    authDomain: 'expense-tracker-d0642.firebaseapp.com',
    storageBucket: 'expense-tracker-d0642.appspot.com',
    measurementId: 'G-5P9WVJQ0VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1aNSJQoQBQ8wYqpx46hCbB-Z9Zsn3_qQ',
    appId: '1:544547051207:android:46e91a4d46d567a86b10e2',
    messagingSenderId: '544547051207',
    projectId: 'expense-tracker-d0642',
    storageBucket: 'expense-tracker-d0642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlUxLUwWN5jnbtvdkwlXXZsZanGsv5SA',
    appId: '1:544547051207:ios:618b4bd84696bd1a6b10e2',
    messagingSenderId: '544547051207',
    projectId: 'expense-tracker-d0642',
    storageBucket: 'expense-tracker-d0642.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOlUxLUwWN5jnbtvdkwlXXZsZanGsv5SA',
    appId: '1:544547051207:ios:618b4bd84696bd1a6b10e2',
    messagingSenderId: '544547051207',
    projectId: 'expense-tracker-d0642',
    storageBucket: 'expense-tracker-d0642.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDATLZrlaLsmqgJgqJDFnLx5QG9vsUnhAE',
    appId: '1:544547051207:web:f134573292b381e26b10e2',
    messagingSenderId: '544547051207',
    projectId: 'expense-tracker-d0642',
    authDomain: 'expense-tracker-d0642.firebaseapp.com',
    storageBucket: 'expense-tracker-d0642.appspot.com',
    measurementId: 'G-FFRCGQLJXZ',
  );
}
